name: armTemplateDeployment

on:
  push:
    branches:
      - main

env:
  subscriptionId: 8c6ccaa9-9f43-4f74-a91e-12a9f922d72c

jobs:
  armDeployStaging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
      resource_group_name: rg-stg-githubactions
      location: Australia East

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Get Key Vault Access Policies
        uses: azure/powershell@v1
        with:
          inlineScript: |
            ./Get-KeyVaultAccessPolicies.ps1 -keyVaultName kv-online-kaptrack-test-ae
          azPSVersion: "latest"

      - name: Get Key Vault Access Policies
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Write-Host ${{ env.keyVaultAccessPolicies }}
          azPSVersion: "latest"

      - name: Deploy key vault
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: ${{ env.resource_group_name }}
          subscriptionId: ${{ env.subscriptionId }}
          template: ./keyvault.json
          parameters: 
            environmentCode=test
            locationCode=ae
            location="${{ env.location }}"
            paralloTagValue=8-5
            accessPolicies=${{ env.keyVaultAccessPolicies }}
          deploymentMode: incremental